swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "API documentaiton for iCycle Malaysia Sdn. Bhd"
host: "petstore.swagger.io"
basePath: "/api/v1.0/"
schemes:
- "https"
- "http"
paths:
  /api/v1.0/orders:
    get:
      tags:
      - "Orders"
      summary: "Get all orders"
      description: ""
      operationId: "get"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - name: "filterHotel"
        in: "query"
        required: false
        type: "string" 
      - name: "filterUser"
        in: "query"
        required: false
        type: "string"
      - name: "fromDateCheckIn"
        in: "query"
        required: false
        type: "string" 
      - name: "toDateCheckIn"
        in: "query"
        required: false
        type: "string"
      - name: "fromDateCheckOut"
        in: "query"
        required: false
        type: "string"
      - name: "toDateCheckOut"
        in: "query"
        required: false
        type: "string" 
      - name: "order"
        in: "query"
        required: false
        type: "string" 
      - name: "sort"
        in: "query"
        required: false
        type: "string" 
      responses:
        "200":
          description: "orders"
      security:
      - Client-key: []
    
    post:
      tags:
      - "Orders"
      summary: "Create an order"
      operationId: "post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "List of user object"
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        "200":
          description: "order"
      security:
      - Client-key: []
      - x-auth: []
      
 
  /api/v1.0/orders/{id}:
    get:
      tags:
      - "Orders"
      summary: "Get an order"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - in: "path"
        type: "string"
        name: "id"
        description: "id of order"
        required: true
      responses:
        "200":
          description: "order"
      security:
      - Client-key: []
      - x-auth: []
  
 
  /api/v1.0/hotels:
    get:
      tags:
      - "Hotels"
      summary: "Get all hotels and rooms"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - in: "query"
        type: "string"
        name: "filter"
        description: "filter for hotel name"
        required: false
      responses:
        "200":
          description: "hotels"
      security:
      - Client-key: []

  /api/v1.0/make-payment/{credit_card}:
    patch:
      tags:
      - "Payment"
      summary: "Make payment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "languageId"
        in: "header"
        required: true
        type: "integer"
        format: "int64"
      - in: "query"
        type: "string"
        name: "id"
        description: "id of the order (the payment_id is in the order object)"
        required: false
      - in: "path"
        type: "string"
        name: "credit_card"
        description: "user's credit card"
        required: true  
      responses:
        "200":
          description: "hotels"
      security:
      - Client-key: []
  
 
  

securityDefinitions:
  Client-key:
    type: "apiKey"
    name: "Client-key"
    in: "header"
definitions:
  Order:
    type: "object"
    properties:
      hotel_id:
        type: "string"
      room_id:
        type: "string"
      number_of_guests:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      email:
        type: "string"
      phone:
        type: "string"
      payment_id:
        type: "string"  
      check_in_date:
        type: "string"
        format: "date-time"
        example: "2020-10-23"
      check_out_date:
        type: "string"
        format: "date-time"
        example: "2020-12-29"  
    xml:
      name: "Order"

  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
